(function () {
    const detailRoute = (template, slug) => `${template}.html?slug=${slug}`;

    const projectDetails = {
        'archive-file-renamer': {
            template: 'project',
            card: {
                icon: '📁',
                title: 'Archive File Renamer',
                description: 'A Python-based GUI utility to transform unorganized media archives into standardized, searchable collections.',
                tools: ['Python', 'Tkinter'],
                tags: ['Automation', 'GUI', 'Operational Efficiency'],
                status: 'Completed',
                year: '2026',
                category: 'analytics', // This places it in the "Data Analytics & Modelling" section
            },
            seoTitle: 'Archive File Renamer | S Adithya',
            description: 'Python GUI utility for batch-renaming and standardizing photo archives using two-pass logic, by S Adithya.',
            heroTag: 'Automation & Productivity',
            heroTitle: 'From Chaos to <span class="highlight">Order</span>',
            heroSub: 'Standardizing digital archives through automated, safe, and sequential file renaming.',
            overviewParagraphs: [
                'Managing large-scale media archives often involves dealing with cryptic, device-generated filenames like "IMG_001" or "WhatsApp_Image_...", which makes searching for specific assets nearly impossible.',
                'This project presents a standalone Python application that acts as a digital librarian, instantly standardizing hundreds of files into a clean, sequential series (e.g., Event_001.jpg) in seconds.',
                'The engine utilizes a <strong style="color:var(--text-primary)">safe two-pass renaming logic</strong>: it first renames files to temporary unique identifiers to clear the naming space, effectively preventing "FileExists" errors and accidental data overwrites.',
                'Originally designed to streamline hostel multimedia operations, the tool supports standard images, iPhone HEIC formats, and professional DSLR RAW files, maintaining perfect chronological order with 3-digit padding.',
            ],
            meta: [
                { label: 'Project Type', value: 'Automation Tool' },
                { label: 'Language', value: 'Python 3' },
                { label: 'GUI Library', value: 'Tkinter' },
                { label: 'Logic', value: 'Two-Pass Sequential' },
                { label: 'Packaging', value: 'PyInstaller (.exe)' },
                { label: 'Year', value: '2026' },
                { label: 'Status', value: 'Completed', tone: 'success' },
            ],
            detailTags: ['Python', 'Automation', 'Desktop App', 'Archival Management', 'Productivity', 'UX Design'],
            insightsIcon: '⚙️',
            insightsTitle: 'Technical Features & Workflow',
            insights: [
                {
                    title: 'Namespace Safety',
                    body: 'Implementation of a <strong style="color: var(--accent);">two-pass rename</strong> ensures that if a file already matches the target pattern, it is temporarily moved rather than causing a system conflict.',
                },
                {
                    title: 'Broad Format Support',
                    body: 'Built to recognize <strong style="color: var(--accent);">standard (JPG), mobile (HEIC), and professional (RAW)</strong> extensions, ensuring a bulletproof experience for diverse multimedia teams.',
                },
                {
                    title: 'Sequential Archiving',
                    body: 'Uses <strong style="color: var(--accent);">three-digit padding (001, 002...)</strong> to ensure that over 100+ files stay in perfect alphabetical and numerical order within system explorers.',
                },
                {
                    title: 'Zero-Install Deployment',
                    body: 'Packaged as a <strong style="color: var(--accent);">standalone executable</strong> via PyInstaller, allowing non-technical users to run the tool without having a Python environment installed.',
                },
            ],
            ctaTitle: 'Source Code & Executable',
            ctaText: 'The full source code, building instructions, and the portable Windows executable are available on my GitHub repository.',
            links: [
                {
                    variant: 'github',
                    label: 'View on GitHub',
                    href: 'https://github.com/anbudanadithya/archive-files-renamer',
                },
            ],
        },

        'ml-classification': {
            template: 'project',
            card: {
                icon: '🎵',
                title: 'Spotify Tracks Popularity Classification',
                description: 'A machine learning model that classifies Spotify tracks into popularity tiers using audio features and metadata.',
                tools: ['Python', 'Scikit-learn'],
                tags: ['Random Forest', 'Data Preprocessing', 'Model Evaluation'],
                status: 'Completed',
                year: '2026',
                category: 'analytics',
            },
            seoTitle: 'Spotify Popularity Classification | S Adithya',
            description: 'Machine learning project using Python and scikit-learn to classify Spotify tracks into High, Medium, or Low popularity tiers.',
            heroTag: 'Machine Learning',
            heroTitle: 'Spotify Tracks <span class="highlight">Popularity Classification</span>',
            heroSub: 'Machine learning project using Python and scikit-learn to classify Spotify tracks into High, Medium, or Low commercial popularity.',
            overviewParagraphs: [
                'The music industry spends millions signing artists, producing albums, and funding campaigns, often without a strong data-driven basis for deciding which songs deserve that investment.',
                'This project asks a direct question relevant to record labels: can we predict whether a song will become a chart-topper, a mainstream track, or remain largely undiscovered before release?',
                'Using Spotify audio measurements for 114,000 songs across 114 genres, I built a Random Forest classifier to place each track into one of three popularity categories: High, Medium, or Low.',
                'The model achieved a <strong style="color:var(--text-primary)">74% accuracy and a weighted F1-score of 72.7%</strong>, making it a practical screening tool for guiding marketing decisions.',
                'This project was undertaken as part of my machine learning course during my MBA program.',
            ],
            meta: [
                { label: 'Dataset', value: 'Spotify Tracks Dataset' },
                { label: 'Source', value: 'Kaggle' },
                { label: 'Algorithm', value: 'Random Forest' },
                { label: 'Tools', value: 'Python + Scikit-learn' },
                { label: 'Year', value: '2026' },
                { label: 'Status', value: 'Completed', tone: 'success' },
            ],
            detailTags: ['Python', 'Scikit-learn', 'Random Forest', 'Machine Learning', 'Data Preprocessing', 'Model Evaluation'],
            insightsIcon: '🎵',
            insightsTitle: 'Model Performance &amp; Key Findings',
            insights: [
                {
                    title: 'Model Accuracy',
                    body: '<strong style="color: var(--accent);">74% accuracy</strong> achieved using a Random Forest classifier across High, Medium, and Low popularity tiers.',
                },
                {
                    title: 'F1-Score',
                    body: '<strong style="color: var(--accent);">Weighted F1-score: 72.7%</strong>, indicating balanced performance across all three classes.',
                },
                {
                    title: 'Feature Importance',
                    body: 'Audio features such as <strong style="color: var(--accent);">energy, danceability, and valence</strong> emerged as strong predictors of popularity.',
                },
                {
                    title: 'Business Impact',
                    body: 'The model can help record labels identify <strong style="color: var(--accent);">high-potential tracks</strong> before release and allocate marketing spend more strategically.',
                },
            ],
            ctaTitle: 'Full Project &amp; Code',
            ctaText: 'The full notebook, preprocessing steps, model training pipeline, and related files are available on GitHub and Kaggle.',
            links: [
                {
                    variant: 'github',
                    label: 'View on GitHub',
                    href: 'https://github.com/AnbudanAdithya/spotify-popularity-prediction',
                },
                {
                    variant: 'kaggle',
                    label: 'View on Kaggle',
                    href: 'https://www.kaggle.com/datasets/anbudanadithya05/spotify-music',
                },
            ],
        },
        'iran-israel-media': {
            template: 'project',
            card: {
                icon: '📝',
                title: 'Global Media Framing Analysis - Iran Israel War',
                description: 'Cross-layer analysis of global sentiment across media channels, editorial opinions, and public opinion on the Iran-Israel war.',
                tools: ['Python', 'Google Cloud API'],
                tags: ['Topic Modelling', 'Sentiment Analysis', 'NLP'],
                status: 'Completed',
                year: '2026',
                category: 'analytics',
            },
            seoTitle: 'Iran-Israel Media Framing Analysis | S Adithya',
            description: 'Cross-layer sentiment analysis of media framing, editorial opinions, and public discourse on the Iran-Israel conflict using NLP, LDA topic modelling, and web scraping.',
            heroTag: 'Text &amp; Web Analytics',
            heroTitle: 'One War, <span class="highlight">Many Narratives</span>',
            heroSub: 'A cross-layer sentiment analysis of media framing, editorial opinions, and public discourse on the Iran-Israel conflict.',
            overviewParagraphs: [
                'This project is undertaken to analyze how global media channels portray the same war with different narrative lenses. This project consists of a cross layer synthesis of how different media outlets frames the current war with different themes. This analysis is added with an analysis of editorial opinions and public opinions (via social media comments) to identify the gaps in media framing and public sentiment. to identify the key themes and sentiments across different media channels and public discourse.',
                'The project utilises <strong style="color:var(--text-primary)">LDA topic modelling and sentiment analysis NLP techniques</strong> in python. Kindly note that the results are purely based out of results arrived at from the text mining through the program. This may or may not be true in the real sense. It is just an attempt to understand whether perspective differences persist among different global media outlets in narrating the same war.',
                'This project was undertaken as part of my text analytics course during my MBA program',
            ],
            meta: [
                { label: 'Dataset', value: 'Web Scraping using keywords' },
                { label: 'Media News', value: 'RSS Feed Scraper + News API Scraper' },
                { label: 'Editorial Opinions', value: 'RSS Feed Scraper' },
                { label: 'Youtube Comments', value: 'Google Cloud API Key Scraping' },
                { label: 'Analysis Methods', value: 'LDA, NLP, Sentiment' },
                { label: 'Tools', value: 'Python' },
                { label: 'Year', value: '2026' },
                { label: 'Status', value: 'Completed', tone: 'success' },
            ],
            detailTags: ['Python', 'Web Scraping', 'Visualizations', 'Global Peace', 'NLP', 'Text Analytics'],
            insightsIcon: '🔍',
            insightsTitle: 'Key Analytical Areas',
            insights: [
                {
                    title: 'Topic Modelling',
                    body: 'Examining whether <strong style="color: var(--accent);">different media outlets</strong> from <em>different regions</em> frame the same war through <em>different lenses</em> with contrasting perspectives.',
                },
                {
                    title: 'Text Classification',
                    body: 'Classifying <strong style="color: var(--accent);">news statements</strong> to particular media channels based on <em>repeated usage of specific terms and phrases</em> and <strong style="color: var(--accent);">dominant themes</strong> covered.',
                },
                {
                    title: 'Sentiment Analysis',
                    body: 'Examining how <strong style="color: var(--accent);">sentiment</strong> in language shifted <em>over time</em> and across <strong style="color: var(--accent);">key events</strong> (for all 3 layers: <em>news articles, editorial opinions, and YouTube comments</em>).',
                },
            ],
            ctaTitle: 'Dataset &amp; Project Files',
            ctaText: 'The full repository containing the scraper codes, scraped datasets, analysis files, along with visualizations are publicly available on my GitHub page. Please look at the repository description in GitHub to know fully about it.',
            links: [
                {
                    variant: 'github',
                    label: 'View on GitHub',
                    href: 'https://github.com/anbudanadithya/text_analytics_iran_israel_cross_layer_analysis',
                },
            ],
        },
        'cybersecurity-threat-dashboard': {
            template: 'project',
            card: {
                icon: '🌐',
                title: 'Global Cybersecurity Threat Dashboard',
                description: 'Interactive Power BI dashboard analyzing and visualizing global cybersecurity threats across countries and industries.',
                tools: ['Power BI'],
                tags: ['Power BI', 'Risk Analytics', 'Data Visualization'],
                status: 'Completed',
                year: '2026',
                category: 'analytics',
            },
            seoTitle: 'Global Cybersecurity Threat Dashboard | S Adithya',
            description: 'Interactive Power BI dashboard analyzing and visualizing global cybersecurity threats across countries and industries. Leveraging comprehensive threat data to identify vulnerabilities and inform strategic risk management decisions.',
            heroTag: 'Data &amp; Risk Analytics',
            heroTitle: 'Global Cybersecurity <span class="highlight">Threat Dashboard</span>',
            heroSub: 'Interactive analysis and visualization of global cybersecurity threats to inform strategic risk management and defense mechanisms.',
            overviewParagraphs: [
                'This project presents an interactive Power BI dashboard designed to analyze and visualize global cybersecurity threats. The dashboard transforms raw threat data into actionable visual insights, providing a comprehensive overview of the evolving cybersecurity landscape worldwide.',
                'By examining attack vectors, geographic vulnerabilities, and threat severity patterns across different countries and industries, this project identifies critical risk areas and suggests defense mechanisms that organizations can adopt. The analysis is grounded in real-world cyber incident data spanning multiple years, offering both strategic and tactical insights for cybersecurity decision-making.',
                'This project was undertaken as part of my MBA program, combining data analytics with cybersecurity risk management principles.',
            ],
            meta: [
                { label: 'Dataset', value: 'Global Cybersecurity Threats (2015-2024)' },
                { label: 'Data Source', value: 'Kaggle - Cyber Incidents' },
                { label: 'Primary Tool', value: 'Microsoft Power BI' },
                { label: 'Visualization Type', value: 'Interactive Dashboard' },
                { label: 'Analysis Scope', value: 'Geographic &amp; Industry' },
                { label: 'Key Metrics', value: 'Threat Severity &amp; Frequency' },
                { label: 'Year', value: '2026' },
                { label: 'Status', value: 'Completed', tone: 'success' },
            ],
            detailTags: ['Power BI', 'Data Visualization', 'Cybersecurity', 'Risk Analytics', 'Business Intelligence', 'Strategic Analysis'],
            insightsIcon: '🔍',
            insightsTitle: 'Key Analytical Insights',
            insights: [
                {
                    title: 'Geographic Vulnerabilities',
                    body: 'Identification of <strong style="color: var(--accent);">high-risk countries</strong> and regions with elevated cyber threat exposure, analyzing <em>attack frequency</em> and <em>severity patterns</em> across geographies.',
                },
                {
                    title: 'Industry Risk Assessment',
                    body: 'Analysis of cyber threat distribution across <strong style="color: var(--accent);">different industries</strong>, identifying which sectors face the <em>greatest exposure</em> to specific <strong style="color: var(--accent);">attack vectors</strong>.',
                },
                {
                    title: 'Attack Vector Analysis',
                    body: 'Examination of <strong style="color: var(--accent);">threat types</strong> and <em>attack patterns</em>, revealing <strong style="color: var(--accent);">prevalent threats</strong> and their <em>temporal trends</em> to support <em>proactive defense strategies</em>.',
                },
            ],
            ctaTitle: 'Dashboard &amp; Project Files',
            ctaText: 'The complete project including the Power BI dashboard file, analytical report, and processed dataset are publicly available on my GitHub repository. Explore the interactive dashboard to discover global cybersecurity threat patterns and strategic insights.',
            links: [
                {
                    variant: 'github',
                    label: 'View on GitHub',
                    href: 'https://github.com/AnbudanAdithya/Global_Cybersecurity_Threat_Dashboard',
                },
            ],
        },
        'bike-analytics': {
            template: 'project',
            card: {
                icon: '📈',
                title: 'Business Analytics Dashboard',
                description: 'An interactive business analytics dashboard built with R and Power BI to identify the drivers of bike purchase decisions.',
                tools: ['R', 'Power BI'],
                tags: ['Logistic Regression', 'Data Analytics'],
                status: 'Completed',
                year: '2025',
                category: 'analytics',
            },
            seoTitle: 'Bike Sales Analytics Dashboard | S Adithya',
            description: 'Business analytics project using R (logistic regression) and Power BI to identify key drivers of bike purchase decisions. Dataset: 1K rows from Kaggle.',
            heroTag: 'Business Analytics',
            heroTitle: 'Bike Sales <span class="highlight">Analytics Dashboard</span>',
            heroSub: 'Identifying key drivers of bike purchase decisions using logistic regression in R and Power BI visualisation.',
            overviewParagraphs: [
                'This business analytics project analyses a dataset of 1,000 bike sales records to uncover the demographic and financial factors that most strongly influence whether a customer purchases a bike. The analysis pipeline runs end-to-end from raw data cleaning to a fully visualised Power BI dashboard.',
                'This project was undertaken as part of my business analytics course during my MBA program',
                'The core model is a <strong style="color:var(--text-primary)">logistic regression</strong> built in R, which predicts the probability of a bike purchase based on variables such as income, age, commute distance, marital status, and region. The results are then visualised in Power BI to surface actionable insights for marketing and sales strategy.',
            ],
            meta: [
                { label: 'Dataset', value: 'Bike Sales - 1K Rows' },
                { label: 'Source', value: 'Kaggle' },
                { label: 'Model', value: 'Logistic Regression' },
                { label: 'Tools', value: 'R + Power BI' },
                { label: 'Year', value: '2025' },
                { label: 'Status', value: 'Completed', tone: 'success' },
            ],
            detailTags: ['R Script', 'Logistic Regression', 'Power BI', 'Data Analytics', 'Business Intelligence', 'Data Cleaning'],
            insightsIcon: '🔍',
            insightsTitle: 'Key Analytical Areas',
            insights: [
                {
                    title: 'Income Analysis',
                    body: 'Examining how <strong style="color: var(--accent);">customer income levels</strong> correlate with <em>bike purchase likelihood</em> across different demographics.',
                },
                {
                    title: 'Commute Distance',
                    body: 'Analysing whether <em>proximity to work</em> drives <strong style="color: var(--accent);">bike adoption</strong> - a key variable in the <em>logistic model</em>.',
                },
                {
                    title: 'Age &amp; Demographics',
                    body: 'Segmenting <strong style="color: var(--accent);">purchase behaviour</strong> by <em>age group, marital status, and number of children</em>.',
                },
                {
                    title: 'Regional Trends',
                    body: 'Comparing <strong style="color: var(--accent);">purchase rates</strong> across <em>North America, Europe, and Pacific</em> regions to identify <strong style="color: var(--accent);">market opportunities</strong>.',
                },
            ],
            ctaTitle: 'Dataset &amp; Project Files',
            ctaText: 'The complete code and dataset used in this analysis are publicly available on GitHub and Kaggle. GitHub includes the R script and Power BI files, while Kaggle provides the full dataset with detailed documentation.',
            links: [
                {
                    variant: 'github',
                    label: 'View on GitHub',
                    href: 'https://github.com/AnbudanAdithya/Bike-sales-business-analytics',
                },
                {
                    variant: 'kaggle',
                    label: 'View on Kaggle',
                    href: 'https://www.kaggle.com/datasets/anbudanadithya05/bike-sales',
                },
            ],
        },
        'pdf-cleaner': {
            template: 'project',
            card: {
                icon: '📑',
                title: 'PDF Content Extractor',
                description: 'A precision document tool that optimizes complex academic PDFs for LLM ingestion by stripping graphical noise.',
                tools: ['Python', 'PyMuPDF (fitz)', 'Coordinate Mapping'],
                tags: ['Automation', 'NLP', 'Data Normalization'],
                status: 'Completed',
                year: '2026',
                category: 'analytics',
            },
            seoTitle: 'PDF Content Extractor | S Adithya',
            heroTag: 'Document Intelligence',
            heroTitle: 'Optimizing Data for <span class="highlight">AI Ingestion</span>',
            heroSub: 'Stripping visual complexity to deliver 99% lighter, signal-pure data streams for Large Language Models.',
            overviewParagraphs: [
                'Academic journals and corporate reports often contain heavy visual formatting—sidebars, background vectors, and professional fonts—that create "noise" for LLM parsers and increase token consumption.',
                'The <span class="highlight">PDF Content Extractor</span> solves this by performing a precision coordinate-based reconstruction. It maps every character to its original (X, Y) pixel location while replacing complex font data with standard, lightweight system fonts.',
                'The result is a structurally identical PDF that is ~99% smaller in file size (e.g., 8MB reduced to 22KB), ensuring zero text overlap and maximum semantic fidelity for RAG systems and AI summarization.',
            ],
            meta: [
                { label: 'Efficiency', value: '99% Size Reduction' },
                { label: 'Core Engine', value: 'PyMuPDF (fitz)' },
                { label: 'Optimization', value: 'Coordinate Mapping' },
                { label: 'Status', value: 'Deployed', tone: 'success' },
            ],
            detailTags: ['Python', 'Document AI', 'PDF Processing', 'Data Normalization', 'Automation', 'LLM Optimization'],
            insightsIcon: '🔬',
            insightsTitle: 'Technical Optimization Strategy',
            insights: [
                {
                    title: 'Coordinate Fidelity',
                    body: 'Uses precise <strong style="color: var(--accent);">pixel-origin mapping</strong> to ensure text stays in its original column or sidebar without the overlaps common in standard extraction.',
                },
                {
                    title: 'Metadata Stripping',
                    body: 'Wipes all <strong style="color: var(--accent);">non-semantic binary data</strong>, including embedded professional fonts and hidden publisher metadata, creating a pure data stream.',
                },
                {
                    title: 'Character Normalization',
                    body: 'Implements a <strong style="color: var(--accent);">custom replacement layer</strong> for academic typography (ligatures, smart quotes), preventing encoding errors in AI processing.',
                }
            ],
            ctaTitle: 'Source Code &amp; Usage Guide',
            ctaText: 'The full source code, along with a detailed usage guide, is available on GitHub for anyone looking to optimize their documents for AI applications.',
            links: [
                { variant: 'github', label: 'View on Github', href: 'https://github.com/AnbudanAdithya/pdf-text-extractor' },
            ],
        },
        'mba-dissertation-f-score': {
            template: 'project',
            card: {
                icon: '📚',
                title: 'MBA Dissertation - Piotroski F-Score',
                description: 'MBA dissertation examining whether Piotroski\'s F-Score works in India\'s NSE 100 and whether a graduated A-Score improves investor returns.',
                tools: ['Excel', 'Capitaline'],
                tags: ['Piotroski F-Score', 'Value Investing', 'NSE 100'],
                status: 'Completed',
                year: '2026',
                category: 'equity',
            },
            seoTitle: 'MBA Dissertation - Piotroski F-Score | S Adithya',
            description: 'MBA dissertation testing Piotroski\'s F-Score in India\'s NSE 100 and comparing it against a graduated A-Score extension.',
            heroTag: 'MBA Dissertation',
            heroTitle: 'Beyond Binary: <span class="highlight">Piotroski F-Score</span>',
            heroSub: 'An MBA dissertation testing whether a modified Piotroski\'s F-Score outperforms the original Piotroski\'s F-Score within India\'s NSE 100 value universe.',
            overviewParagraphs: [
                'This dissertation studies whether Piotroski\'s F-Score can reliably separate financially strong value stocks from weak ones in India\'s NSE 100 universe. It also tests a modified A-Score framework that assigns graduated weights to the original nine signals instead of using a pure binary system.',
                'The research covers <strong style="color:var(--text-primary)">189 unique NSE 100 companies</strong> across a <strong style="color:var(--text-primary)">12-year sample from July 2013 to June 2025</strong>. Each year, the top 30% of stocks by book-to-market ratio are identified as value stocks, and both models are tested on the same sample.',
                'The key conclusion is clear: the original binary F-Score remains the more reliable strategy in this universe. The long-only strong portfolio materially outperforms the NIFTY 100 benchmark, while the more complex A-Score fails to produce better strong-weak separation.',
            ],
            meta: [
                { label: 'Study Universe', value: 'NSE 100 Value Stocks' },
                { label: 'Sample Period', value: 'July 2013 - June 2025' },
                { label: 'Coverage', value: '189 Companies | 1,049 Firm-Years' },
                { label: 'Models Tested', value: 'F-Score and A-Score' },
                { label: 'Tools', value: 'Excel + Capitaline' },
                { label: 'Year', value: '2026' },
                { label: 'Status', value: 'Completed', tone: 'success' },
            ],
            detailTags: ['MBA Dissertation', 'Piotroski F-Score', 'Value Investing', 'NSE 100', 'Fundamental Analysis', 'Indian Equity Market'],
            insightsIcon: '📊',
            insightsTitle: 'Key Statistical Highlights',
            insights: [
                {
                    title: 'Full Sample Performance',
                    body: 'The original <strong style="color: var(--accent);">F-Score strong portfolio returned 25.18%</strong> annually versus a <strong style="color: var(--accent);">14.63% NIFTY 100 benchmark</strong>, with statistical significance at <strong style="color: var(--accent);">p = 0.029</strong>.',
                },
                {
                    title: 'Non-Financial Subsample',
                    body: 'After excluding financial firms, the strong portfolio return improved to <strong style="color: var(--accent);">29.29%</strong> with <strong style="color: var(--accent);">p = 0.044</strong>, while the strong-weak spread widened to <strong style="color: var(--accent);">14.77%</strong>.',
                },
                {
                    title: 'A-Score Did Not Win',
                    body: 'The graduated A-Score failed to outperform the original model. In the full sample, its strong-weak spread was only <strong style="color: var(--accent);">0.09%</strong>, and the study ultimately <strong style="color: var(--accent);">rejected H2</strong>.',
                },
                {
                    title: 'Practical Takeaway',
                    body: 'For NSE 100 investors, the dissertation recommends focusing on <strong style="color: var(--accent);">F-Score &ge; 7</strong>, which delivered roughly <strong style="color: var(--accent);">10% to 15% annual outperformance</strong> over the benchmark on average.',
                },
            ],
            ctaTitle: 'Full Dissertation PDF',
            ctaText: 'The complete dissertation can be opened directly in a new tab as a PDF. It includes the full methodology, hypothesis testing, portfolio construction framework, and all supporting tables.',
            links: [
                {
                    variant: 'document',
                    label: 'Open Dissertation PDF',
                    href: '../assets/PDF/MBA%20Dissertation_F-Score.pdf',
                },
            ],
        },
        apollo: {
            template: 'report',
            card: {
                icon: '🏥',
                title: 'Apollo Hospitals Equity Research',
                description: 'A fundamental analysis report covering industry positioning, financial ratios, valuation, and an investment recommendation.',
                tools: [],
                tags: ['Equity Research', 'Fundamental Analysis', 'Valuation'],
                status: 'Completed',
                year: '2025',
                category: 'equity',
            },
            seoTitle: 'Apollo Hospitals Fundamental Analysis | S Adithya',
            description: 'In-depth equity research on Apollo Hospitals covering qualitative factors, Porter\'s 5 Forces, financial ratios, and investment recommendation.',
            heroTag: 'Fundamental Analysis',
            heroTitle: 'Apollo Hospitals <span class="highlight">Fundamental Analysis</span>',
            heroSub: 'A comprehensive evaluation of the economic, industry, and financial fundamentals of Apollo Hospitals, covering Qualitative factors, Porter\'s 5 Fores, Financial Ratios and Investment Recommendation.',
            reportTitle: 'Analysis Report',
            pdfPath: '../assets/PDF/Fundamental_Analysis.pdf',
            pdfFrameTitle: 'Apollo Hospitals Fundamental Analysis Report',
        },
        'tata-motors': {
            template: 'report',
            card: {
                icon: '🚗',
                title: 'Tata Motors Financial Analysis',
                description: 'A comprehensive evaluation of Tata Motors through financial statements, cash flow trends, and ratio analysis.',
                tools: [],
                tags: ['Financial Analysis', 'Ratio Analysis', 'Corporate Finance'],
                status: 'Completed',
                year: '2024',
                category: 'equity',
            },
            seoTitle: 'Tata Motors Financial Analysis | S Adithya',
            description: 'Comprehensive financial statement analysis of Tata Motors using income statements, balance sheets, and core financial ratios.',
            heroTag: 'Stock Analysis',
            heroTitle: 'Tata Motors <span class="highlight">Financial Analysis</span>',
            heroSub: 'An evaluation of financial health through income statements, balance sheets, and core financial ratios.',
            reportTitle: 'Analysis Report',
            pdfPath: '../assets/PDF/Financial_Analysis.pdf',
            pdfFrameTitle: 'Tata Motors Financial Analysis Report',
        },
        bmc: {
            template: 'report',
            card: {
                icon: '💊',
                title: 'Pfizer: Value Chain &amp; BMC',
                description: 'A strategic analysis of Pfizer using Porter\'s Value Chain Analysis and the Business Model Canvas framework.',
                tools: [],
                tags: ['Business Model Canvas', 'Value Chain Analysis'],
                status: 'Completed',
                year: '2025',
                category: 'strategy',
            },
            seoTitle: 'Pfizer Strategic Analysis | S Adithya',
            description: 'Strategic evaluation of Pfizer using Porter\'s Value Chain Analysis and the Business Model Canvas, by S Adithya.',
            heroTag: 'Business Strategy',
            heroTitle: 'Pfizer: Value Chain &amp; <span class="highlight">BMC</span>',
            heroSub: 'Strategic evaluation using Porter\'s Value Chain and the Business Model Canvas.',
            reportTitle: 'Analysis Report',
            pdfPath: '../assets/PDF/BMC.pdf',
            pdfFrameTitle: 'Pfizer Value Chain and BMC Report',
        },
        'product-study': {
            template: 'report',
            card: {
                icon: '🎯',
                title: 'Product Idea Market Study',
                description: 'An in-depth market research study evaluating feasibility, target demographics, and the competitive landscape for a new concept.',
                tools: [],
                tags: ['Market Research', 'Business Strategy', 'Consumer Behavior'],
                status: 'Completed',
                year: '2024',
                category: 'strategy',
            },
            seoTitle: 'Product Idea Market Study | S Adithya',
            description: 'An in-depth market study evaluating feasibility, target demographics, and competitive landscape for a new product concept, by S Adithya.',
            heroTag: 'Product Study',
            heroTitle: 'Product Idea <span class="highlight">Market Study</span>',
            heroSub: 'An in-depth evaluation of feasibility, target demographics, and the competitive landscape for a new product concept.',
            reportTitle: 'Research Report',
            pdfPath: '../assets/PDF/Guardian_X.pdf',
            pdfFrameTitle: 'Product Idea Market Study Report',
        },
        'fintech-report': {
            template: 'report',
            card: {
                icon: '📱',
                title: 'FinTech Banks Report',
                description: 'A research report analysing the rise of FinTech banks, their operating models, and their disruption of traditional banking.',
                tools: [],
                tags: ['Market Research', 'FinTech', 'Business Strategy'],
                status: 'Completed',
                year: '2023',
                category: 'strategy',
            },
            seoTitle: 'FinTech Banks Report | S Adithya',
            description: 'Research report analysing the rise of FinTech banks, their operational models, and disruption of traditional banking, by S Adithya.',
            heroTag: 'Industry Study',
            heroTitle: 'FinTech Banks - <span class="highlight">Sector Study</span>',
            heroSub: 'Analyzing the rise of FinTech banks, operational models, and their disruption of traditional banking.',
            reportTitle: 'Research Report',
            pdfPath: '../assets/PDF/FinTech_Banks.pdf',
            pdfFrameTitle: 'FinTech Banks Sector Study Report',
        },
        'book-review': {
            template: 'report',
            card: {
                icon: '📖',
                title: 'Book Review',
                description: 'A critical review of The Psychology of Money exploring foundational principles of personal finance and behavioural investing.',
                tools: [],
                tags: ['Personal Finance', 'Behavioral Investing', 'Book Analysis'],
                status: 'Completed',
                year: '2023',
                category: 'strategy',
            },
            seoTitle: 'Critical Book Review | S Adithya',
            description: 'A critical book review of The Psychology of Money completed during Undergrad, by S Adithya.',
            heroTag: 'Book Review',
            heroTitle: 'Critical Book <span class="highlight">Review</span>',
            heroSub: 'A comprehensive book review of Psychology of Money completed as part of my Undergrad project.',
            reportTitle: 'Review Report',
            pdfPath: '../assets/PDF/Book_Review.pdf',
            pdfFrameTitle: 'Psychology of Money Book Review Report',
        },
    };

    const toResearchCard = (slug) => {
        const detail = projectDetails[slug];
        return {
            ...detail.card,
            link: detailRoute(detail.template, slug),
        };
    };

    const projectModels = [
        {
            icon: '📊',
            title: 'Portfolio Optimization Model',
            description: 'Built using Modern Portfolio Theory to estimate efficient portfolios, risk-return trade-offs, and allocation decisions.',
            tools: ['Python', 'NumPy'],
            tags: ['Monte Carlo', 'MPT', 'Efficient Frontier'],
            status: 'Coming Soon',
            year: '2026',
            link: null,
        },
        {
            icon: '💰',
            title: 'Payback Period Calculator',
            description: 'Interactive model to calculate simple and discounted payback periods with fixed-growth and uneven cash flow patterns.',
            tools: ['Excel', 'VBA'],
            tags: ['DCF', 'Capital Budgeting', 'Calculator'],
            status: 'Completed',
            year: '2026',
            link: 'payback.html',
        },
    ];

    const projectResearch = [
        toResearchCard('pdf-cleaner'),
        toResearchCard('archive-file-renamer'),
        toResearchCard('mba-dissertation-f-score'),
        toResearchCard('ml-classification'),
        toResearchCard('iran-israel-media'),
        toResearchCard('cybersecurity-threat-dashboard'),
        toResearchCard('bike-analytics'),
        toResearchCard('apollo'),
        toResearchCard('tata-motors'),
        toResearchCard('bmc'),
        toResearchCard('product-study'),
        toResearchCard('fintech-report'),
        toResearchCard('book-review'),
    ];

    window.projectModels = projectModels;
    window.projectResearch = projectResearch;
    window.projectDetails = projectDetails;
}());
